### ISSUE TITLE
URL in yammer posts should point back to badge app site

### ISSUE THREAD

**Issue by rockfordlhotka** [Magenic/Badge-Application#251]
The URL in a yammer post right now points to a non-existent location on Magenic.com.

The URL _should_ point to the badge application site itself, and specifically to the user's "salad bar":

`https://badgeapplication.magenic.com/Leaderboard/show/<username>`

**Comment by BillZiss** [comment]
I have coded a fix that is ready for deployment by Kevin Ford.
