### ISSUE TITLE
As an approver, I should get notified when a badge needs approval

### ISSUE THREAD

**Issue by rockfordlhotka** [Magenic/Badge-Application#252]
To keep this decoupled from any particular notification technology, perhaps this should be done via web events or some other scheme that can be hooked up via IFTTT or Flow?

**Comment by Bowman74** [comment]
Went live, 4/18/2017, waiting for results before closing.

**Comment by rockfordlhotka** [comment]
In talking to @Bowman74 it sounds like this was implemented to send an email via SMTP, but was probably never rolled into production.

At this point though, it should not use SMTP. It should trigger a Flow.

**Comment by Stormin808** [comment]
currently implemented as SMTP. A separate issue will be needed to redesign it as a Flow implementation.
