### ISSUE TITLE
Switch notifications from yammer to teams

### ISSUE THREAD

**Issue by rockfordlhotka** [Magenic/Badge-Application#257]
Switch the notifications for badges so they end up in Microsoft Teams instead of in yammer.

Perhaps better yet would be to have the notifications appear as a web event that can be handled by Flow, and then use a Flow to relay the notification to anywhere we choose (right now that'd be Teams).

**Comment by Stormin808** [comment]
this has been completed. Posts are to Magenic...General channel in Microsoft Teams.
